name = "castar-auth"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "castar-db"
database_id = "e658fde0-7bbe-46ad-a52e-0c528bfba242"

# Secrets (set via `wrangler secret put`):
# JWT_SECRET
# RESEND_API_KEY
# ESKIZ_TOKEN
# TELEGRAM_BOT_TOKEN
# GOOGLE_CLOUD_STT_KEY
